const $=id=>document.getElementById(id);let me=null,geo=[];
function toast(msg,ok=false){const t=$('toast');t.textContent=msg;t.className='toast show '+(ok?'ok':'err');clearTimeout(window.__t);window.__t=setTimeout(()=>t.className='toast',3000)}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('hidden',x.id!==id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const titles={dashboard:['Dashboard','Business overview'],parcel:['Add Parcel','Create and send a Steadfast parcel'],orders:['Orders','CN# and Tracking ID'],expenses:['Expenses','Business expenses'],suppliers:['Suppliers','Supplier management'],settings:['Settings','Account & Steadfast API']};$('pageTitle').textContent=titles[id][0];$('pageSub').textContent=titles[id][1];if(id==='dashboard')loadDashboard();if(id==='orders')loadOrders();if(id==='expenses')loadExpenses();if(id==='suppliers')loadSuppliers();if(id==='settings')loadSettings();}
function money(v){return '৳ '+Number(v||0).toLocaleString('en-BD',{maximumFractionDigits:2})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function setUser(){const u=me?.username||'User';$('sideUser').textContent=u;$('helloUser').textContent=u;$('settingsUser').textContent=u;$('avatar').textContent=u[0].toUpperCase();$('settingsAvatar').textContent=u[0].toUpperCase()}
async function boot(){try{const d=await api('/api/auth/me');if(d.ok){me=d;setUser();$('auth').classList.add('hidden');$('app').classList.remove('hidden');await loadGeo();await refreshApiPill();openTab('dashboard')}}catch{}}
async function loadGeo(){try{const d=await api('/api/locations/districts');geo=d.data||[];const sel=$('district');sel.innerHTML='<option value="">Select District</option>'+geo.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')}catch(e){toast('District list load failed: '+e.message)}}
$('district').onchange=async()=>{const d=$('district').value;const s=$('thana');s.innerHTML='<option value="">Loading…</option>';s.disabled=true;if(!d){s.innerHTML='<option value="">Select District first</option>';return}try{const r=await api('/api/locations/upazilas?district='+encodeURIComponent(d));s.innerHTML='<option value="">Select Thana / Upazila</option>'+(r.data||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');s.disabled=false}catch(e){s.innerHTML='<option value="">Unable to load</option>';toast(e.message)}};
async function refreshApiPill(){try{const d=await api('/api/config');$('apiPill').textContent=d.steadfast_configured?'✓ Steadfast connected':'API not connected';$('apiPill').className='pill '+(d.steadfast_configured?'ok':'off');$('connectionText').textContent=d.steadfast_configured?'Your Steadfast account is connected and ready to send parcels.':'Add your API Key and Secret Key from Settings.'}catch{}}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('loginUser').value,password:$('loginPass').value})});me=await api('/api/auth/me');setUser();$('auth').classList.add('hidden');$('app').classList.remove('hidden');await loadGeo();await refreshApiPill();openTab('dashboard');toast('Welcome back!',true)}catch(x){toast(x.message)}};
$('registerForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/register',{method:'POST',body:JSON.stringify({username:$('regUser').value,password:$('regPass').value})});me=await api('/api/auth/me');setUser();$('auth').classList.add('hidden');$('app').classList.remove('hidden');await loadGeo();openTab('settings');toast('Account created. Add your Steadfast API.',true)}catch(x){toast(x.message)}};
document.querySelectorAll('.auth-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm').classList.toggle('hidden',b.dataset.auth!=='login');$('registerForm').classList.toggle('hidden',b.dataset.auth!=='register')});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('mobile-open');
$('logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});location.reload()};
async function loadDashboard(){try{const d=await api('/api/dashboard');const arr=[['Total Orders',d.total_orders,'▣'],['Delivered',d.delivered,'✓'],['Pending',d.pending,'◷'],['Cancelled',d.cancelled,'!'],['Total Sales',money(d.sales),'৳'],['Supplier Cost',money(d.supplier_cost),'♙'],['Other Expenses',money(d.other_expenses),'−'],['Net Profit',money(d.net_profit),'↗']];$('stats').innerHTML=arr.map(x=>`<div class="stat"><span>${x[2]} &nbsp; ${x[0]}</span><b>${x[1]}</b></div>`).join('')}catch(e){toast(e.message)}}
function parcelData(){return{invoice:$('invoice').value,recipient_name:$('customer_name').value,recipient_phone:$('customer_phone').value,alternative_phone:$('alternative_phone').value,recipient_email:$('recipient_email').value,recipient_address:$('address').value,district:$('district').value,thana:$('thana').value,cod_amount:Number($('cod_amount').value||0),weight:Number($('weight').value||1),total_lot:Number($('total_lot').value||1),delivery_type:Number($('delivery_type').value||0),supplier_name:$('supplier_name').value,supplier_cost:Number($('supplier_cost').value||0),delivery_charge:Number($('delivery_charge').value||0),item_description:$('item_description').value,note:$('note').value}}
function resetParcel(){document.getElementById('parcelForm').reset();$('weight').value=1;$('total_lot').value=1;$('supplier_cost').value=0;$('delivery_charge').value=0;$('thana').disabled=true;$('thana').innerHTML='<option value="">Select District first</option>'}
$('parcelForm').onsubmit=async e=>{e.preventDefault();const b=$('sendNow');b.disabled=true;b.textContent='Sending…';try{const d=await api('/api/parcels',{method:'POST',body:JSON.stringify(parcelData())});const p=d.parcel;toast(`Sent ✓  CN#: ${p.consignment_id||'N/A'}  •  Tracking: ${p.tracking_code||'N/A'}`,true);resetParcel();openTab('orders')}catch(x){toast(x.message)}finally{b.disabled=false;b.textContent='🚚 Save & Send to Steadfast'}};
$('saveOnly').onclick=async()=>{const data=parcelData();try{const p=await api('/api/parcels',{method:'POST',body:JSON.stringify(data)});toast(`Saved. CN#: ${p.parcel.consignment_id||'Pending'} • Tracking: ${p.parcel.tracking_code||'Pending'}`,true);resetParcel();openTab('orders')}catch(e){toast(e.message)}};
async function loadOrders(){try{const q=encodeURIComponent($('orderSearch').value||'');const rows=await api('/api/parcels?q='+q);$('ordersBody').innerHTML=rows.map(o=>rowHtml(o)).join('');$('mobileOrders').innerHTML=rows.map(mobileRow).join('')||'<div class="muted">No orders found.</div>'}catch(e){toast(e.message)}}
function rowHtml(o){return `<tr><td><div class="id-box"><b>${esc(o.invoice)}</b><small>${esc(o.created_at)}</small></div></td><td><b>${esc(o.recipient_name)}</b><br><small>${esc(o.recipient_phone)}<br>${esc(o.district)}, ${esc(o.thana)}</small></td><td>${money(o.cod_amount)}</td><td><span class="code">${esc(o.consignment_id||'—')}</span></td><td><span class="code">${esc(o.tracking_code||'—')}</span></td><td><span class="status ${esc(o.status)}">${esc(o.status)}</span></td><td><button class="secondary" onclick="refreshParcel(${o.id})">↻ Sync</button></td></tr>`}
function mobileRow(o){return `<div class="order-card"><div class="row"><b>${esc(o.invoice)}</b><span class="status ${esc(o.status)}">${esc(o.status)}</span></div><div class="muted">${esc(o.recipient_name)} • ${esc(o.recipient_phone)}</div><div class="row"><span>CN#</span><span class="code">${esc(o.consignment_id||'—')}</span></div><div class="row"><span>Tracking</span><span class="code">${esc(o.tracking_code||'—')}</span></div><div class="row"><b>${money(o.cod_amount)}</b><button class="secondary" onclick="refreshParcel(${o.id})">↻ Sync</button></div></div>`}
$('orderSearch').oninput=()=>{clearTimeout(window.searchTimer);window.searchTimer=setTimeout(loadOrders,300)};
async function refreshParcel(id){try{const d=await api('/api/parcels/'+id+'/refresh',{method:'POST'});toast(`Updated • CN#: ${d.parcel.consignment_id||'—'} • Tracking: ${d.parcel.tracking_code||'—'}`,true);loadOrders();loadDashboard()}catch(e){toast(e.message)}}
async function loadExpenses(){try{const r=await api('/api/expenses');$('expenseList').innerHTML=r.map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><small>${esc(x.note||'')}</small></div><b>${money(x.amount)}</b></div>`).join('')||'<span class="muted">No expenses yet.</span>'}catch(e){toast(e.message)}}
$('expenseForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/expenses',{method:'POST',body:JSON.stringify({title:$('expense_title').value,amount:Number($('expense_amount').value),note:$('expense_note').value})});e.target.reset();toast('Expense saved',true);loadExpenses();loadDashboard()}catch(x){toast(x.message)}};
async function loadSuppliers(){try{const r=await api('/api/suppliers');$('supplierList').innerHTML=r.map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><small>${esc(x.phone||'')}<br>${esc(x.address||'')}</small></div><div><b>Paid ${money(x.paid)}</b><small>Due ${money(x.due)}</small></div></div>`).join('')||'<span class="muted">No suppliers yet.</span>'}catch(e){toast(e.message)}}
$('supplierForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/suppliers',{method:'POST',body:JSON.stringify({name:$('supplier_name2').value,phone:$('supplier_phone').value,address:$('supplier_address').value,paid:Number($('supplier_paid').value||0),due:Number($('supplier_due').value||0)})});e.target.reset();toast('Supplier saved',true);loadSuppliers()}catch(x){toast(x.message)}};
async function loadSettings(){try{const d=await api('/api/settings');$('sfKey').value=d.steadfast_api_key||'';$('sfSecret').value=d.steadfast_secret_key||'';$('settingsMsg').textContent=d.steadfast_api_key?'Credentials saved for this account.':'No credentials saved yet.'}catch(e){toast(e.message)}}
$('testApi').onclick=async()=>{try{const d=await api('/api/settings/test',{method:'POST',body:JSON.stringify({steadfast_api_key:$('sfKey').value,steadfast_secret_key:$('sfSecret').value})});$('settingsMsg').textContent='✓ '+d.message;toast('Steadfast connected',true)}catch(e){$('settingsMsg').textContent='✕ '+e.message;toast(e.message)}};
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/settings',{method:'POST',body:JSON.stringify({steadfast_api_key:$('sfKey').value,steadfast_secret_key:$('sfSecret').value})});await refreshApiPill();$('settingsMsg').textContent='✓ Saved. This API belongs to your account only.';toast('API credentials saved',true)}catch(x){toast(x.message)}};
boot();

// Beautiful dashboard quick-order form + mobile navigation
function fillDistrictSelect(id){const s=$(id);if(!s)return;s.innerHTML='<option value="">Select District</option>'+geo.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')}
function bindDistrictPair(did,tid){const d=$(did),t=$(tid);if(!d||!t)return;d.onchange=async()=>{const v=d.value;t.innerHTML='<option value="">Loading…</option>';t.disabled=true;if(!v){t.innerHTML='<option value="">Select District first</option>';return}try{const r=await api('/api/locations/upazilas?district='+encodeURIComponent(v));t.innerHTML='<option value="">Select Thana / Upazila</option>'+(r.data||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');t.disabled=false}catch(e){t.innerHTML='<option value="">Unable to load</option>';toast(e.message)}}}
const oldLoadGeo=loadGeo;
loadGeo=async()=>{await oldLoadGeo();fillDistrictSelect('q_district');bindDistrictPair('q_district','q_thana');};
$('quickOrderForm').onsubmit=async e=>{e.preventDefault();$('customer_name').value=$('q_customer').value;$('customer_phone').value=$('q_phone').value;$('invoice').value=$('q_invoice').value;$('item_description').value=$('q_product').value;$('district').value=$('q_district').value;await $('district').onchange();$('thana').value=$('q_thana').value;$('address').value=$('q_address').value;$('cod_amount').value=$('q_cod').value;$('weight').value=$('q_weight').value;document.getElementById('parcelForm').requestSubmit();};
$('logoutTop').onclick=async()=>{$('logout').click()};
